"""
config.py - Configuration and thresholds for the AI Code Review Bot.
"""

from typing import Literal

# ---------------------------------------------------------------------------
# Path filtering
# ---------------------------------------------------------------------------

# Files whose paths contain any of these substrings will be skipped entirely.
IGNORED_PATHS: list[str] = [
    "node_modules",
    ".lock",          # package-lock.json, yarn.lock, poetry.lock, etc.
    "dist/",
    "build/",
    ".min.js",
    ".min.css",
    "__pycache__",
    ".pyc",
    "migrations/",    # Django / Alembic auto-generated migrations
    "vendor/",
    ".pb.go",         # Protobuf generated files
    "_pb2.py",        # Protobuf Python generated
    "*.generated.*",
]

# ---------------------------------------------------------------------------
# Severity thresholds
# ---------------------------------------------------------------------------

# Only findings at or above this severity level will be posted as inline
# comments.  Allowed values: "critical" | "warning" | "minor"
MIN_SEVERITY_TO_POST: Literal["critical", "warning", "minor"] = "warning"

SEVERITY_ORDER: dict[str, int] = {
    "critical": 3,
    "warning": 2,
    "minor": 1,
}

# ---------------------------------------------------------------------------
# API / run caps
# ---------------------------------------------------------------------------

# Maximum number of files to send to Claude per run.  Files beyond this limit
# are logged as skipped.
MAX_FILES_PER_RUN: int = 20

# Files with more changed lines than this threshold are skipped (too large to
# review reliably in a single prompt).
MAX_DIFF_LINES_PER_FILE: int = 500

# ---------------------------------------------------------------------------
# Comment formatting
# ---------------------------------------------------------------------------

REVIEW_HEADER: str = (
    "## 🤖 AI Code Review\n\n"
    "Automated review generated by **gemini-code-reviewer**.\n"
    "Findings are ordered by severity. Please address **critical** issues before merging.\n\n"
)

REVIEW_FOOTER: str = (
    "\n\n---\n"
    "_This review was generated automatically. "
    "False positives may occur — use your own judgement._"
)
